name: 2p2t
version: '1.0-SNAPSHOT'
main: me.playstation451.2p2tcore.Core2p2t
api-version: 1.21
folia-supported: true

commands:
  p2t:
    description: P2tCore commands.
    usage: /2p2t [reload]
    permission: p2t.admin
    permission-message: You do not have permission to use this command.